"""add tournament display config

Revision ID: 582be5286725
Revises: 657302df78d5
Create Date: 2026-08-29 07:15:21.507732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '582be5286725'
down_revision: Union[str, None] = '657302df78d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default matches the precedent in
    # 8d55ec2b6640_tournament_forms_and_onboarded_at.py's `prerequisites`
    # column — existing rows backfill to {} rather than failing NOT NULL.
    op.add_column('tournaments', sa.Column('display_config', sa.JSON(), nullable=False, server_default=sa.text("'{}'::json")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'display_config')
    # ### end Alembic commands ###
