"""add unique constraint on tournament shift track and label

Revision ID: 5b5c2f46ad06
Revises: 9beadc61ad5a
Create Date: 2026-09-17 16:44:41.701310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b5c2f46ad06'
down_revision: Union[str, None] = '9beadc61ad5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_tournament_shift_track_label', 'tournament_shifts', ['track_id', 'label'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tournament_shift_track_label', 'tournament_shifts', type_='unique')
    # ### end Alembic commands ###
