"""add unique constraint on tournament shift track and label

Revision ID: 5b5c2f46ad06
Revises: 9beadc61ad5a
Create Date: 2026-09-17 16:44:41.701310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b5c2f46ad06'
down_revision: Union[str, None] = '9beadc61ad5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Existing data may already hold duplicate (track_id, label) pairs. Rename
    # rather than merge: shifts are referenced by events, assignments and
    # availability, so merging means re-pointing FKs and risks unique clashes.
    # The oldest row keeps its label; later ones become "Label (2)", "(3)"...
    op.execute("""
        UPDATE tournament_shifts s
        SET label = left(s.label, 245) || ' (' || d.rn || ')'
        FROM (
            SELECT id, row_number() OVER (PARTITION BY track_id, label ORDER BY id) AS rn
            FROM tournament_shifts
        ) d
        WHERE s.id = d.id AND d.rn > 1
    """)
    op.create_unique_constraint('uq_tournament_shift_track_label', 'tournament_shifts', ['track_id', 'label'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tournament_shift_track_label', 'tournament_shifts', type_='unique')
    # ### end Alembic commands ###
