"""add tournament membership age disclosure

Revision ID: 657302df78d5
Revises: e38f3f7cddb9
Create Date: 2026-08-29 01:59:48.426273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '657302df78d5'
down_revision: Union[str, None] = 'e38f3f7cddb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_memberships', sa.Column('age_disclosure', sa.String(length=32), nullable=True))
    op.add_column('tournament_memberships', sa.Column('age_disclosure_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_memberships', 'age_disclosure_at')
    op.drop_column('tournament_memberships', 'age_disclosure')
    # ### end Alembic commands ###
