"""drop key from tournament_roles

Revision ID: 8226e1d280b0
Revises: faa21d1f5a4a
Create Date: 2026-08-06 14:01:52.651337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8226e1d280b0'
down_revision: Union[str, None] = 'faa21d1f5a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tournament_role_key', 'tournament_roles', type_='unique')
    op.create_unique_constraint('uq_tournament_role_label', 'tournament_roles', ['tournament_id', 'label'])
    op.drop_column('tournament_roles', 'key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_roles', sa.Column('key', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint('uq_tournament_role_label', 'tournament_roles', type_='unique')
    op.create_unique_constraint('uq_tournament_role_key', 'tournament_roles', ['tournament_id', 'key'])
    # ### end Alembic commands ###
