"""add tournament age disclosure toggles

Revision ID: e38f3f7cddb9
Revises: 8e43330211be
Create Date: 2026-08-29 01:55:17.226245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e38f3f7cddb9'
down_revision: Union[str, None] = '8e43330211be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default so existing rows backfill to false rather than failing
    # the NOT NULL constraint — the model's Python-side default only applies
    # to new rows.
    op.add_column('tournaments', sa.Column('collect_is_over_18', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('tournaments', sa.Column('collect_is_over_21', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'collect_is_over_21')
    op.drop_column('tournaments', 'collect_is_over_18')
    # ### end Alembic commands ###
