"""add user fields and lunch_order json

Revision ID: e975e198a8e1
Revises: b2c3d4e5f6a7
Create Date: 2026-03-28 13:46:15.901067

Adds student_status, competition_exp, volunteering_exp columns to users table.
Changes lunch_order on memberships from String(255) to JSON.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e975e198a8e1'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("memberships") as batch_op:
        batch_op.alter_column('lunch_order',
                existing_type=sa.VARCHAR(length=255),
                type_=sa.JSON(),
                existing_nullable=True,
                postgresql_using='lunch_order::json')
    op.add_column('users', sa.Column('student_status', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('competition_exp', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('volunteering_exp', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'volunteering_exp')
    op.drop_column('users', 'competition_exp')
    op.drop_column('users', 'student_status')
    with op.batch_alter_table("memberships") as batch_op:
        batch_op.alter_column('lunch_order',
                existing_type=sa.JSON(),
                type_=sa.VARCHAR(length=255),
                existing_nullable=True)
    # ### end Alembic commands ###
