"""add_year_level_and_graduation_year_to_users

Revision ID: ef714fead897
Revises: 2f2394fbbc02
Create Date: 2026-06-19 18:08:16.299942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef714fead897'
down_revision: Union[str, None] = '2f2394fbbc02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('year_level', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('graduation_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'graduation_year')
    op.drop_column('users', 'year_level')
    # ### end Alembic commands ###
